### ISSUE TITLE
The mssql dialect does not work with owners other than dbo.

### ISSUE THREAD

**Issue by hamster1979** [davideairaghi/php#5]
tip:  change in dialect php file describeColumns to 
```
public function describeColumns($table, $schema = null)
{
      $sql = "exec sp_columns [$table] , [$schema]";
      return $sql;
}
```
then in Model php $this->setSchema('Owner'); will work to change owner of table.

**Comment by davideairaghi** [comment]
thank you for your suggestion, i just commited the change in describeColumns.
