### ISSUE TITLE
WordPress Extra File Types: Request for adding .docx extension

### ISSUE THREAD

**Issue by lanshunfang** [davideairaghi/php#7]
Hi David, 

Sorry for bothering you in Github. I found you are the author of https://www.airaghi.net/blog/2015/01/02/wordpress-extra-file-types/?hilite=%27WP%27%2C%27Extra%27%2C%27File%27%2C%27Types%27

The Wordpress plugin has many file types built-in, but not docx - MS Word main stream file. I am wondering if possible for you to add that.

Name: MS Word
extension: docx
MIME: application/vnd.openxmlformats-officedocument.wordprocessingml.document

Refer to: 
- https://stackoverflow.com/questions/4212861/what-is-a-correct-mime-type-for-docx-pptx-etc
- https://wordpress.org/plugins/wp-extra-file-types/

Thanks very much.
Paul

**Comment by davideairaghi** [comment]
you can configure new file types by yourself using plugin's settings page.
have you already tried to do that ? is so, how have you configured it ? (a screenshot to see could be very useful to help you)

**Comment by lanshunfang** [comment]
Yep, I've done that and it works. This issue is just for other users' convenience. 

![image](https://user-images.githubusercontent.com/1013667/50747015-b0978a00-126c-11e9-903a-7703192bd3c8.png)
